// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Account struct {
	AccountID      int64     `json:"account_id"`
	DocumentNumber string    `json:"document_number"`
	CreatedAt      time.Time `json:"created_at"`
}

type OperationType struct {
	OperationTypeID int64  `json:"operation_type_id"`
	Description     string `json:"description"`
}

type Transaction struct {
	TransactionID   int64 `json:"transaction_id"`
	OperationTypeID int64 `json:"operation_type_id"`
	AccountID       int64 `json:"account_id"`
	// can be negative or positive
	Amount    float64   `json:"amount"`
	EventDate time.Time `json:"event_date"`
}
