// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: operation_type.sql

package db

import (
	"context"
)

const getOperationType = `-- name: GetOperationType :one
SELECT operation_type_id, description FROM operation_types
WHERE operation_type_id = $1 LIMIT 1
`

func (q *Queries) GetOperationType(ctx context.Context, operationTypeID int64) (OperationType, error) {
	row := q.db.QueryRowContext(ctx, getOperationType, operationTypeID)
	var i OperationType
	err := row.Scan(&i.OperationTypeID, &i.Description)
	return i, err
}
