// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: transaction.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    account_id,
    operation_type_id,
    amount
) VALUES (
    $1, $2, $3
) RETURNING transaction_id, operation_type_id, account_id, amount, event_date
`

type CreateTransactionParams struct {
	AccountID       int64 `json:"account_id"`
	OperationTypeID int64 `json:"operation_type_id"`
	Amount          int64 `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.AccountID, arg.OperationTypeID, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OperationTypeID,
		&i.AccountID,
		&i.Amount,
		&i.EventDate,
	)
	return i, err
}
